### ISSUE TITLE
Splash screen not showing, config probably not updated on server?

### ISSUE THREAD

**Issue by MartijnKooij** [PsiOps/MyFoosTracker#2]
My recently completed PR #1 did not solve the issue of the 404 on the splash screen. If I debug the cordova splash screen plugin code on the deployed website I see that I still get an undefined value back from the config.xml.
Can you check whether you have deployed the config? I have exactly 0 experience with deploying Firebase apps so I have no idea what I'm talking about 😄 

![image](https://user-images.githubusercontent.com/3163541/52814412-663fcf00-309c-11e9-9fab-e71fa12a7b42.png)

**Comment by PsiOps** [comment]
There are so many ways to build an ionic cordova app, but only one way to deploy to firebase. The command is `firebase deploy` and that's just it. I have no way of inspecting what the server looks like, that's the beauty of it :). Anyway, I'm now experimenting and reading up on deploying a PWA with ionic. I don't think I need to include cordova at all, which may fix the splashscreen issue altogether. Hopefully all the other things will keep working. Thanks for looking with me, you put me on the right track @MartijnKooij !

**Comment by PsiOps** [comment]
I sort of think I got it now. I think the trick was to not build with `ionic cordova build browser --prod --service-worker` but with `ionic build --prod --service-worker`. So cordova is not included at all then (which generates a couple of warnings in the log now, but those I can also fix I think), and no splashscreen is attempted! Can you confirm this @MartijnKooij ?

**Comment by MartijnKooij** [comment]
I can confirm that I no longer see any splash screen attempt. Was that your goal? I think the deployed site does not even contain the installed cordova splash plugin anymore?

Anyways, it's better than the 404, a bit of a waste of all my Paint.net design skills on the splash image though ;)

**Comment by PsiOps** [comment]
Yeah the goal was to remove the ugly broken splashscreen. The PWA when installed to Home screen displays a proper splashscreen on startup. So that's good enough for now. Closing this issue!
